package com.activitytrace.ui

import android.content.Context
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.pluralStringResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.activitytrace.BuildConfig
import com.activitytrace.R
import com.activitytrace.demo.DemoDataRepository
import com.activitytrace.demo.DemoDataScenario
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DemoDataScreen(
    onBack: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val repository = remember(context) { DemoDataRepository.getInstance(context) }

    val showcaseCount by repository.recordCount(DemoDataScenario.SHOWCASE).collectAsState(initial = 0)
    val benchmarkCount by repository.recordCount(DemoDataScenario.SEARCH_BENCHMARK).collectAsState(initial = 0)

    var busy by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }
    var lastGenerated by remember { mutableStateOf(repository.lastGeneratedAt(DemoDataScenario.SHOWCASE)) }
    var confirmReset by remember { mutableStateOf(false) }
    var confirmClearAll by remember { mutableStateOf(false) }

    fun runGeneration(scenario: DemoDataScenario, regenerate: Boolean = false) {
        scope.launch {
            busy = true
            error = null
            runCatching {
                if (regenerate) repository.regenerate(scenario) else repository.generate(scenario)
                lastGenerated = repository.lastGeneratedAt(scenario)
            }.onFailure {
                error = context.getString(R.string.demo_data_error_occurred)
            }
            busy = false
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.demo_data_title)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(R.string.back_description),
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface,
                ),
            )
        },
        modifier = modifier,
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .navigationBarsPadding()
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
        ) {
            Text(
                text = stringResource(R.string.demo_data_description),
                style = MaterialTheme.typography.bodyLarge,
            )

            Spacer(Modifier.height(16.dp))
            Text(
                text = stringResource(R.string.demo_data_what_it_contains),
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )

            Spacer(Modifier.height(24.dp))
            if (showcaseCount > 0) {
                ShowcaseStatusCard(
                    count = showcaseCount,
                    lastGeneratedAt = lastGenerated,
                    context = context,
                )
                Spacer(Modifier.height(12.dp))
            }

            if (busy) {
                Row {
                    CircularProgressIndicator(modifier = Modifier.size(20.dp))
                    Spacer(Modifier.width(12.dp))
                    Text(stringResource(R.string.demo_data_busy))
                }
                Spacer(Modifier.height(12.dp))
            }

            Button(
                onClick = { runGeneration(DemoDataScenario.SHOWCASE) },
                enabled = !busy,
            ) {
                Text(stringResource(if (showcaseCount > 0) R.string.demo_data_regenerate else R.string.demo_data_generate))
            }

            if (showcaseCount > 0) {
                Spacer(Modifier.height(8.dp))
                OutlinedButton(
                    onClick = { confirmReset = true },
                    enabled = !busy,
                ) {
                    Text(stringResource(R.string.demo_data_reset))
                }
            }

            if (error != null) {
                Spacer(Modifier.height(12.dp))
                Text(
                    text = error.orEmpty(),
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodyMedium,
                )
            }

            if (BuildConfig.DEBUG) {
                Spacer(Modifier.height(32.dp))
                DebugBenchmarkSection(
                    benchmarkCount = benchmarkCount,
                    busy = busy,
                    onGenerateBenchmark = { runGeneration(DemoDataScenario.SEARCH_BENCHMARK, regenerate = true) },
                    onClearAll = { confirmClearAll = true },
                )
            }
        }
    }

    if (confirmReset) {
        AlertDialog(
            onDismissRequest = { confirmReset = false },
            title = { Text(stringResource(R.string.demo_data_reset_title)) },
            text = { Text(stringResource(R.string.demo_data_reset_message)) },
            confirmButton = {
                TextButton(
                    onClick = {
                        confirmReset = false
                        scope.launch {
                            busy = true
                            repository.clear(DemoDataScenario.SHOWCASE)
                            lastGenerated = -1L
                            busy = false
                        }
                    },
                ) {
                    Text(stringResource(R.string.reset))
                }
            },
            dismissButton = {
                TextButton(onClick = { confirmReset = false }) {
                    Text(stringResource(R.string.cancel))
                }
            },
        )
    }

    if (confirmClearAll) {
        AlertDialog(
            onDismissRequest = { confirmClearAll = false },
            title = { Text(stringResource(R.string.demo_data_clear_all_title)) },
            text = { Text(stringResource(R.string.demo_data_reset_message)) },
            confirmButton = {
                TextButton(
                    onClick = {
                        confirmClearAll = false
                        scope.launch {
                            busy = true
                            repository.clear(DemoDataScenario.SHOWCASE)
                            repository.clear(DemoDataScenario.SEARCH_BENCHMARK)
                            lastGenerated = -1L
                            busy = false
                        }
                    },
                ) {
                    Text(stringResource(R.string.delete))
                }
            },
            dismissButton = {
                TextButton(onClick = { confirmClearAll = false }) {
                    Text(stringResource(R.string.cancel))
                }
            },
        )
    }
}

@Composable
private fun ShowcaseStatusCard(
    count: Int,
    lastGeneratedAt: Long,
    context: Context,
) {
    val generatedLabel = remember(lastGeneratedAt) {
        if (lastGeneratedAt > 0) {
            val date = java.time.Instant.ofEpochMilli(lastGeneratedAt)
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate()
                .format(java.time.format.DateTimeFormatter.ofLocalizedDate(java.time.format.FormatStyle.MEDIUM))
            context.getString(R.string.demo_data_generated_on, date)
        } else {
            context.getString(R.string.demo_data_not_generated)
        }
    }
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = pluralStringResource(R.plurals.demo_data_captures, count, count),
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.SemiBold,
            )
            Spacer(Modifier.height(4.dp))
            Text(
                text = generatedLabel,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

@Composable
private fun DebugBenchmarkSection(
    benchmarkCount: Int,
    busy: Boolean,
    onGenerateBenchmark: () -> Unit,
    onClearAll: () -> Unit,
) {
    Text(
        text = stringResource(R.string.demo_data_developer_options),
        style = MaterialTheme.typography.titleMedium,
        fontWeight = FontWeight.SemiBold,
    )
    Spacer(Modifier.height(8.dp))
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = if (benchmarkCount > 0) {
                    pluralStringResource(R.plurals.demo_data_captures, benchmarkCount, benchmarkCount)
                } else {
                    stringResource(R.string.demo_data_benchmark_empty)
                },
                style = MaterialTheme.typography.bodyLarge,
            )
            Spacer(Modifier.height(8.dp))
            Button(
                onClick = onGenerateBenchmark,
                enabled = !busy,
            ) {
                Text(stringResource(R.string.demo_data_generate_benchmark))
            }
            Spacer(Modifier.height(8.dp))
            OutlinedButton(
                onClick = onClearAll,
                enabled = !busy,
            ) {
                Text(stringResource(R.string.demo_data_clear_all))
            }
        }
    }
}